### ISSUE TITLE
Glyphs 3: needs to use GSLayer.metrics

### ISSUE THREAD

**Issue by mekkablue** [mekkablue/ShowTopsAndBottoms#11]
For Glyphs 3, the glyphs need to display red or grey bars according to `GSLayer.metrics` (not `GSFontMaster.xHeight`, etc.). But functionality for Glyphs 2 must stay the same.

Probably best to separate into different functions, and use a try/except construction:

```
try:
	# call function for GLYPHS 3
	# produce an error for G2
except:
	# call function forGLYPHS 2
```

**Comment by RafalBuchner** [comment]
I based version checker on Glyphs.versionNumber, rather than on try/except.
I also made zone placement based on layer.metrics for glyphs3.
