### ISSUE TITLE
Keyboard shortcut overwrites existing use of shortcut

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/ShowTopsAndBottoms#13]
The keyboard shortcut used (Ctrl+Opt+Cmd+T) overwrites existing use of shortcut. Is it hardcoded?

**Comment by mekkablue** [comment]
There is nothing I can do about it from within the plug-in except remove the shortcut altogether.

**Comment by clauseggers** [comment]
Alrighty then. Is the situation just that the keyboard shortcut situation in Glyphs is not sophisticated enough to deal with these collisions?
