### ISSUE TITLE
namespace the class in plugin.py

### ISSUE THREAD

**Issue by schriftgestalt** [mekkablue/ShowTopsAndBottoms#2]
The class needs to have a unique name otherwise you can install more than one of this plugins. Add a suffix to the class name.

**Comment by schriftgestalt** [comment]
When the new plugin code is finished, the base classes will move to a global module/import. Then they can use the same name.

**Comment by mekkablue** [comment]
Not sure I did it right in v.1.0.2. Do I just need to change the name of the class, or also the plugin.py file name? I changed both now.
